# Generated by Django 4.1.2 on 2022-10-13 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor_cache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=200)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.sensor')),
            ],
        ),
    ]
