# Generated by Django 4.1.2 on 2022-10-14 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_sensor_cache'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='state',
            field=models.CharField(choices=[('on', 'ON'), ('off', 'OFF')], default='off', max_length=100),
        ),
    ]
