# Generated by Django 4.1.2 on 2022-10-24 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_condition_smartcondition_sensorstate_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
